//lists all the actions types

export const CREATE_APPLET='CREATE_APPLET';
export const OFF_APPLET='OFF_APPLET';
export const ON_APPLET='ON_APPLET';
export const SHOW_APPLET='SHOW_APPLET';


export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const SET_USER_FROM_LOCALSTORAGE = 'SET_USER_FROM_LOCALSTORAGE';

export const CHANGING_PASS = 'CHANGING_PASS';
export const CHANGING_PASS_SUCCESS = 'CHANGING_PASS_SUCCESS';
export const CHANGING_PASS_FAILURE = 'CHANGING_PASS_FAILURE';
export const SUCCESS_OFF = 'SUCCESS_OFF'

export const CHANGING_EMAIL = 'CHANGING_EMAIL';
export const CHANGING_EMAIL_SUCCESS = 'CHANGING_EMAIL_SUCCESS';
export const CHANGING_EMAIL_FAILURE = 'CHANGING_EMAIL_FAILURE';

export const LINK_FB = 'LINK_FB';
export const LINK_GOOGLE = 'LINK_GOOGLE';

export const ACCOUNT_DELETION = 'ACCOUNT_DELETION';
export const ACCOUNT_DELETION_SUCCESS = 'ACCOUNT_DELETION_SUCCESS';
export const ACCOUNT_DELETION_FAILURE = 'ACCOUNT_DELETION_FAILURE';


export const RENDER_SNACKBAR = 'RENDER_SNACKBAR';
export const CLOSE  = 'CLOSE';